### ISSUE TITLE
Duplicate `kernel_arguments` fields in openshift 4.9.0-exp spec

### ISSUE THREAD

**Issue by bgilbert** [coreos/butane#237]
`openshift/4.9.0-exp` supports the new Ignition kargs fields, which are handled by Ignition on first boot, as well as the `openshift.kernel_arguments` field, which is handled by the MCO.  This is confusing.  We could make the `openshift` one an alias for the Ignition one, or disable one or the other, or very carefully document when each should be used.

**Comment by jlebon** [comment]
Hmm, one difference though is that the MCO only knows how to append, not remove. Would it make sense to instead make the `openshift` one an alias for `should_exist`? (Although it's not exactly the same semantics because IIRC the MCO always appends rather than checking first.)

That implies teaching the MCO about the new fields.

**Comment by bgilbert** [comment]
The lack of removal support in the MCO is unfortunate, but fixing it isn't in scope for now.  The agreed-upon plan for 4.9 is that the MCO will support configs declaring a 3.3.0 spec version, but only if those configs can be downconverted to 3.2.0.  (That is, the MCO will still use 3.2.0 structs internally.)
