### ISSUE TITLE
Make experimental spec stabilization smoother

### ISSUE THREAD

**Issue by jlebon** [coreos/butane#451]
In the latest `1.5.0` stabilization, there were a lot of churn across multiple repos (at least this one, https://github.com/coreos/coreos-assembler, https://github.com/coreos/fedora-coreos-config, and https://github.com/openshift/os) and branches within these repos that required tweaking because we had tests that used the `1.5.0-experimental` spec.

What are some ways we could make stabilization smoother in the future?

**Comment by jlebon** [comment]
One crude idea is to have some kind of hidden `BUTANE_UNSUPPORTED_ALLOW_EXPERIMENTAL` env var knob where `1.5.0-experimental` could be parsed as if it were `1.5.0` temporarily to increase the window of time available for transition.

**Comment by bgilbert** [comment]
The main issue is the Ignition/Butane ratchet, which was unusually protracted this time, and the inability to revendor Ignition into cosa without also updating Butane.  https://github.com/coreos/coreos-assembler/pull/3422 should remove the cosa codebase from the critical part of that ratchet, so that the process will just require updating tests in fedora-coreos-config and openshift/os.

AIUI there was another issue this cycle, where some RHCOS 4.13 CI was running on cosa `main` and some was running on `rhcos-4.13`.  The cosa PR should prevent that from causing an issue, though of course we should also try not to do it.

**Comment by bgilbert** [comment]
Checklist update in https://github.com/coreos/ignition/pull/1607.
